// Data teks untuk latihan mengetik & soal HOTS berpikir komputasional
// Materi dibedakan per tingkat kelas:
//  - Kelas 7: pengenalan komputer & dampak teknologi (paling dasar)
//  - Kelas 8: pengenalan konsep dasar berpikir komputasional di kehidupan sehari-hari
//  - Kelas 9: laporan terstruktur dengan judul, sub-judul (#, ##, ###) + isu teknologi modern

export type GradeLevel = '7A' | '7B' | '7C' | '8A' | '8B' | '8C' | '9A' | '9B'

export interface Question {
  id: number
  question: string
  options: string[]
  correctAnswer: number
  explanation: string
  category: string
  // ── Bug #2 fix: add optional imageUrl so gambar soal can render ──
  // The API /api/content/questions returns imageUrl from the Prisma
  // Question model (imageUrl String?). Without this field declared,
  // TypeScript errors out and the runtime check `currentQ.imageUrl && (...)`
  // always evaluates to falsy (undefined), preventing images from rendering.
  imageUrl?: string | null
}

// =====================================================
// TEKS MENGETIK — Kelas 8: teks naratif panjang (plain)
// Kelas 9: laporan terstruktur (markdown #, ##, ###)
// =====================================================

export const TYPING_TEXTS: Record<GradeLevel, string> = {
  // ---- Kelas 7A: Mengenal Komputer dan Dampak Teknologi ----
  '7A': `Komputer adalah alat elektronik yang sangat penting dalam kehidupan kita saat ini. Hampir setiap hari kita melihat dan menggunakan komputer, baik di rumah, di sekolah, maupun di tempat umum. Komputer digunakan untuk berbagai keperluan, seperti menulis, menghitung, menggambar, bermain game, mencari informasi di internet, dan berkomunikasi dengan orang lain yang jauh. Komputer terdiri dari dua bagian utama, yaitu perangkat keras dan perangkat lunak. Perangkat keras adalah bagian komputer yang bisa kita lihat dan sentuh, seperti monitor, keyboard, mouse, dan printer. Monitor berfungsi untuk menampilkan gambar dan tulisan. Keyboard digunakan untuk mengetik huruf dan angka. Mouse digunakan untuk menggerakkan kursor di layar. Printer digunakan untuk mencetak dokumen di atas kertas. Perangkat lunak adalah program yang ada di dalam komputer dan tidak bisa kita sentuh. Contoh perangkat lunak adalah sistem operasi, aplikasi pengolah kata, aplikasi presentasi, dan game. Komputer bekerja dengan cara menerima data dari pengguna, memproses data tersebut, lalu menghasilkan informasi yang bisa kita gunakan. Komputer sangat membantu kita dalam belajar. Dengan komputer, kita bisa mencari informasi untuk tugas sekolah, membuat presentasi yang menarik, dan belajar berbagai keterampilan baru. Namun, kita juga harus berhati-hati saat menggunakan komputer. Terlalu lama di depan komputer bisa membuat mata lelah dan tubuh kurang bergerak. Selain itu, tidak semua informasi di internet itu benar, jadi kita harus pintar memilih sumber yang tepercaya. Komputer juga bisa digunakan untuk hal yang buruk, seperti menyebarkan berita bohong atau mencuri data orang lain. Oleh karena itu, kita harus menggunakan komputer dengan bijak dan bertanggung jawab. Teknologi terus berkembang dari waktu ke waktu. Dulu komputer berukuran sangat besar dan hanya digunakan oleh ilmuwan. Sekarang komputer bisa kita simpan di saku dalam bentuk ponsel pintar. Perkembangan teknologi ini membuat hidup kita menjadi lebih mudah, tapi juga menuntut kita untuk terus belajar agar tidak tertinggal. Mari kita gunakan komputer dengan baik untuk hal-hal yang bermanfaat dan jangan lupa untuk tetap berinteraksi dengan teman dan keluarga di dunia nyata.`,

  // ---- Kelas 7B: Penggunaan Teknologi yang Sehat dan Bertanggung Jawab ----
  '7B': `Di zaman sekarang, hampir semua orang memiliki ponsel pintar. Ponsel pintar adalah alat komunikasi yang sangat canggih. Kita bisa menelepon, mengirim pesan, mengambil foto, merekam video, mendengarkan musik, menonton film, dan mencari informasi di internet. Ponsel pintar juga bisa digunakan untuk berbagai aplikasi, seperti media sosial, aplikasi belanja, aplikasi pembayaran, dan aplikasi pembelajaran. Meskipun ponsel pintar sangat berguna, kita harus menggunakanannya dengan bijak. Terlalu lama bermain ponsel bisa membuat kita lupa waktu, mengabaikan tugas sekolah, dan jarang berinteraksi dengan orang di sekitar kita. Banyak anak yang kecanduan game atau media sosial sehingga waktu belajar dan istirahatnya berkurang. Akibatnya, nilai pelajaran menurun dan kesehatan tubuh terganggu. Oleh karena itu, kita perlu mengatur waktu penggunaan ponsel. Berikut adalah beberapa tips menggunakan ponsel dengan bijak. Pertama, tentukan berapa lama waktu untuk bermain ponsel setiap hari, misalnya maksimal dua jam. Kedua, jangan gunakan ponsel saat makan bersama keluarga atau saat sedang belajar. Ketiga, matikan ponsel saat tidur agar tidak terganggu notifikasi. Keempat, pilih aplikasi yang bermanfaat untuk belajar atau mengembangkan keterampilan. Kelima, jangan percaya semua informasi yang ada di internet, selalu cek kebenarannya. Selain itu, kita juga harus menjaga keamanan saat menggunakan ponsel. Jangan pernah membagikan data pribadi, seperti alamat rumah, nomor rekening, atau password, kepada orang yang tidak dikenal di internet. Waspadai juga penipuan online yang sering terjadi, seperti pesan yang menawarkan hadiah gratis atau meminta transfer uang. Jika menerima pesan mencurigakan, segera beritahu orang tua atau guru. Teknologi memang membuat hidup kita lebih mudah, tetapi kita harus tetap menggunakan akal sehat dan hati-hati. Jangan sampai kita menjadi budak teknologi, tetapi jadilah penguasa teknologi yang bijak. Dengan demikian, ponsel pintar akan menjadi alat yang membantu kita berkembang, bukan sebaliknya. Mari mulai dari sekarang untuk menggunakan ponsel dengan lebih bijak dan bertanggung jawab. Dengan begitu, kita bisa memanfaatkan teknologi untuk hal-hal yang positif tanpa mengorbankan kesehatan, pelajaran, atau hubungan dengan orang-orang di sekitar kita.`,

  // ---- Kelas 7C: Mengenal Internet dan Etika Bermedia Digital ----
  '7C': `Internet adalah jaringan yang menghubungkan jutaan komputer di seluruh dunia. Dengan internet, kita bisa mencari informasi, berkomunikasi, belajar, berbelanja, dan bahkan bekerja dari jarak jauh. Internet membawa banyak manfaat, tetapi juga memiliki risiko yang perlu kita waspadai. Manfaat internet sangat banyak. Pertama, kita bisa mencari informasi dengan cepat. Ingin tahu tentang sejarah Indonesia, cara memasak suatu makanan, atau berita terbaru, semuanya bisa kita temukan di internet. Kedua, internet memudahkan kita berkomunikasi dengan keluarga atau teman yang jauh. Kita bisa menelepon video, mengirim pesan, atau berbagi foto dan video. Ketiga, internet bisa digunakan untuk belajar. Ada banyak video pembelajaran, artikel, dan kursus online yang bisa diikuti gratis. Keempat, internet membuka peluang bisnis baru. Banyak orang yang berhasil berjualan online atau menjadi content creator. Namun, internet juga memiliki risiko. Pertama, ada banyak informasi yang tidak benar atau hoaks. Kita harus pintar memilih sumber yang tepercaya dan selalu cek kebenaran informasi sebelum mempercayainya atau menyebarkannya. Kedua, ada orang jahat yang menggunakan internet untuk menipu atau mencelakai orang lain, seperti penipuan online, pencurian identitas, atau perundungan maya. Ketiga, terlalu lama di internet bisa membuat kita lupa waktu dan mengabaikan aktivitas lain yang penting, seperti belajar, berolahraga, atau bergaul dengan teman. Keempat, ada konten yang tidak pantas untuk anak, seperti kekerasan atau hal-hal negatif lain. Etika bermedia digital sangat penting untuk dipelajari. Berikut beberapa aturan yang harus kita ikuti. Pertama, hormati privasi orang lain. Jangan membagikan foto atau informasi pribadi orang lain tanpa izin. Kedua, gunakan bahasa yang sopan saat berkomunikasi di internet. Jangan menghina, mencaci, atau menyebarkan kebencian. Ketiga, jangan menyebarkan informasi yang belum tentu benar. Selalu cek dulu kebenarannya. Keempat, hormati hak cipta. Jangan menyalin pekerjaan orang lain tanpa menyebut sumbernya. Kelima, jaga keamanan akun. Gunakan password yang kuat dan jangan membagikannya kepada siapapun. Dengan memahami manfaat dan risiko internet, serta menerapkan etika bermedia digital yang baik, kita bisa menjadi pengguna internet yang bijak dan bertanggung jawab. Mari kita gunakan internet untuk hal-hal yang positif dan bermanfaat, bukan untuk hal-hal yang merugikan diri sendiri atau orang lain. Generasi muda adalah penerus bangsa, jadi mari kita tunjukkan bahwa kita bisa menggunakan teknologi dengan bijak untuk kemajuan bersama.`,

  // ---- Kelas 8A ----
  '8A': `Pernahkah kalian memperhatikan bagaimana cara ibu kita memasak nasi di pagi hari? Pertama, ia mengukur beras dengan gelas takaran. Kedua, ia mencuci beras sampai bersih. Ketiga, ia memasukkan beras ke dalam rice cooker dan menambahkan air sesuai takaran. Keempat, ia menekan tombol cook dan menunggu sampai matang. Tahapan-tahapan ini sebenarnya adalah contoh sederhana dari sebuah konsep yang sangat penting di dunia teknologi, yaitu berpikir komputasional. Berpikir komputasional bukan berarti kita harus menjadi programmer atau menghafal bahasa pemrograman yang rumit. Berpikir komputasional adalah cara kita memecahkan masalah secara sistematis, logis, dan terstruktur, layaknya cara kerja sebuah komputer. Ada empat pilar utama dalam berpikir komputasional yang perlu kalian pahami sebagai siswa SMP. Pilar pertama adalah dekomposisi, yaitu kemampuan memecah masalah besar yang rumit menjadi bagian-bagian kecil yang lebih mudah diselesaikan. Sebagai contoh, ketika kalian mendapat tugas membuat poster untuk hari kemerdekaan, kalian tidak langsung menggambar sekaligus. Kalian memecahnya menjadi: menentukan tema, mencari referensi, membuat sketsa, mewarnai, dan menambahkan tulisan. Pilar kedua adalah pengenalan pola, yaitu kemampuan menemukan kesamaan atau pola yang berulang. Ketika kalian belajar matematika dan menemukan pola bilangan dua, empat, enam, delapan, kalian bisa menebak angka berikutnya adalah sepuluh. Itulah pengenalan pola. Pilar ketiga adalah abstraksi, yaitu fokus pada hal-hal penting saja dan mengabaikan detail yang tidak relevan. Saat kalian membuat jadwal pelajaran, kalian hanya menulis nama mapel, jam, dan guru. Kalian tidak perlu menggambar wajah guru atau warna bajunya. Itulah abstraksi. Pilar keempat adalah algoritma, yaitu langkah-langkah berurutan yang jelas untuk menyelesaikan suatu masalah. Resep masakan, cara membuat origami, atau cara login ke akun sekolah semuanya adalah algoritma. Dengan berpikir komputasional, kalian belajar memecahkan masalah dengan lebih tertib dan efisien. Inilah keterampilan penting di abad ke-21, bukan hanya untuk programmer, tetapi untuk semua orang. Ketika kalian terbiasa berpikir komputasional, kalian akan lebih mudah menyelesaikan tugas-tugas sekolah, lebih cepat menemukan solusi atas masalah sehari-hari, dan lebih siap menghadapi dunia kerja di masa depan. Mulai hari ini, mari kita latih keempat pilar ini dalam setiap aktivitas. Pecah masalah besar jadi langkah kecil, cari pola yang berulang, fokus pada hal penting, dan susun urutan langkah dengan jelas. Dengan begitu, kalian bukan hanya pengguna teknologi, tetapi juga pemikir kreatif yang siap menjadi pencipta solusi di masa depan.`,

  // ---- Kelas 8B ----
  '8B': `Setiap pagi sebelum berangkat sekolah, kalian pasti memiliki urutan kegiatan yang sama: bangun tidur, mandi, sarapan, pakai seragam, ambil tas, lalu berangkat. Urutan ini tidak boleh diacak, kan? Kalian tidak bisa pakai seragam sebelum mandi, atau berangkat sebelum ambil tas. Urutan langkah yang harus diikuti secara berurutan inilah yang disebut dengan algoritma. Algoritma adalah salah satu pilar penting dalam berpikir komputasional. Berpikir komputasional sendiri adalah cara berpikir untuk memecahkan masalah secara sistematis seperti cara kerja komputer. Ada empat pilar berpikir komputasional yang perlu kalian kuasai. Pilar pertama, dekomposisi, adalah memecah masalah besar menjadi bagian-bagian kecil. Misalnya, saat kalian ingin mengadakan pesta ulang tahun, kalian memecahnya menjadi: tentukan tema, buat daftar tamu, siapkan makanan, dan susun acara. Setiap bagian menjadi lebih mudah dikerjakan. Pilar kedua, pengenalan pola, adalah mencari kesamaan yang berulang. Di sekolah, kalian mungkin memperhatikan bahwa nilai matematika cenderung lebih baik ketika kalian belajar malam sebelumnya. Itu adalah pola yang bisa kalian manfaatkan untuk meningkatkan prestasi. Pilar ketiga, abstraksi, adalah memilih informasi penting dan mengabaikan yang tidak penting. Peta sekolah yang hanya menampilkan ruang kelas, lapangan, dan toilet adalah contoh abstraksi. Tidak semua detail digambar, hanya yang penting untuk navigasi. Pilar keempat, algoritma, adalah urutan langkah yang jelas dan terbatas. Cara kalian mengirim pesan di WhatsApp adalah algoritma: buka aplikasi, pilih kontak, ketik pesan, lalu tekan kirim. Empat pilar ini bekerja sama dalam setiap teknologi yang kalian gunakan setiap hari. Aplikasi transportasi online, game favorit kalian, hingga smartwatch yang menghitung langkah kaki, semuanya dibangun dengan berpikir komputasional. Bayangkan jika seandainya pembuat aplikasi tidak menggunakan algoritma yang baik, aplikasi tersebut bisa crash, lambat, atau bahkan berbahaya bagi pengguna. Inilah mengapa keterampilan berpikir komputasional sangat penting dipelajari sejak dini. Jadi, mulai sekarang, biasakan berpikir seperti komputer: pecah masalah jadi bagian kecil, cari polanya, fokus pada yang penting, dan susun langkah yang jelas. Dengan begitu, kalian bukan hanya pengguna teknologi, tetapi juga pemikir kreatif yang siap menghadapi masa depan. Kalian bisa mulai melatihnya dari hal-hal sederhana, seperti menyelesaikan PR, mengatur jadwal belajar, atau bahkan membantu ibu di dapur. Setiap masalah yang kalian pecahkan dengan sistematis adalah latihan berpikir komputasional yang berharga. Selamat berlatih, dan jadilah generasi yang tidak hanya pintar menggunakan teknologi, tetapi juga mampu menciptakannya untuk kemajuan bangsa.`,

  // ---- Kelas 8C ----
  '8C': `Bayangkan kalian sedang bermain game puzzle favorit. Untuk menyelesaikan setiap level, kalian harus memikirkan langkah mana yang harus diambil terlebih dahulu, mengenali pola musuh yang muncul, dan fokus pada tujuan utama tanpa terganggu detail kecil. Tanpa kalian sadari, kalian sebenarnya sudah menerapkan berpikir komputasional. Berpikir komputasional adalah keterampilan memecahkan masalah dengan cara yang sistematis, logis, dan terstruktur, mirip dengan cara kerja komputer. Keterampilan ini sangat penting bagi kalian sebagai generasi muda di era digital. Ada empat pilar utama dalam berpikir komputasional. Pilar pertama adalah dekomposisi, yaitu memecah masalah besar menjadi tugas-tugas kecil yang lebih mudah dikerjakan. Misalnya, ketika guru memberi tugas membuat presentasi kelompok, kalian bisa memecahnya menjadi: mencari informasi, membuat slide, menyusun naskah, dan latihan presentasi. Setiap anggota kelompok bisa fokus pada satu tugas. Pilar kedua adalah pengenalan pola, yaitu menemukan kesamaan yang berulang di berbagai situasi. Ketika kalian belajar bahasa Inggris dan melihat pola bahwa kata yang berakhiran -ly biasanya merupakan keterangan, kalian bisa lebih cepat memahami kalimat baru. Itulah kekuatan pengenalan pola. Pilar ketiga adalah abstraksi, yaitu fokus pada informasi yang penting dan mengabaikan yang tidak relevan. Saat kalian menonton video pembelajaran, kalian tidak perlu mengingat warna baju presenter atau latar belakangnya. Yang penting adalah isi materi yang disampaikan. Pilar keempat adalah algoritma, yaitu urutan langkah yang jelas untuk menyelesaikan masalah. Cara kalian membuat akun media sosial adalah algoritma: unduh aplikasi, isi data, buat username dan password, lalu verifikasi. Empat pilar ini bukan teori yang sulit. Kalian sudah menggunakannya setiap hari, mungkin tanpa sadar. Yang perlu kalian lakukan sekarang adalah melatihnya dengan lebih sengaja. Ketika menghadapi soal matematika yang sulit, gunakan dekomposisi. Ketika belajar dari kesalahan, gunakan pengenalan pola. Ketika harus fokus belajar, gunakan abstraksi. Ketika menyelesaikan tugas, susunlah algoritma. Berpikir komputasional akan membuat kalian lebih cerdas dalam memecahkan masalah, lebih kreatif dalam berkarya, dan lebih siap menghadapi tantangan dunia digital di masa depan. Bayangkan jika semua siswa Indonesia terbiasa berpikir seperti ini, betapa banyak masalah yang bisa diselesaikan, betapa banyak inovasi yang bisa lahir. Kalian adalah bagian dari generasi yang akan menentukan arah teknologi di masa depan. Jangan jadi penonton, jadi pelakunya. Mulailah dari hal kecil, pecahkan masalah di sekitar kalian dengan sistematis, dan kalian akan terkejut melihat betapa hebatnya kemampuan yang kalian miliki. Selamat berlatih, semoga kalian menjadi generasi yang siap menghadapi masa depan dengan percaya diri.`,

  // ---- Kelas 9A (laporan terstruktur dengan markdown) ----
  '9A': `# Laporan: Berpikir Komputasional di Era Kecerdasan Buatan

## Pendahuluan

Kecerdasan buatan atau Artificial Intelligence (AI) telah menjadi bagian tak terpisahkan dari kehidupan kita sehari-hari. Dari asisten suara di ponsel, algoritma rekomendasi di media sosial, hingga mobil yang dapat menyetir sendiri, semuanya dibangun di atas fondasi yang sama, yaitu berpikir komputasional. Laporan ini membahas bagaimana berpikir komputasional menjadi keterampilan kunci di era AI.

## Empat Pilar Berpikir Komputasional

### 1. Dekomposisi

Dekomposisi adalah keterampilan memecah masalah besar yang kompleks menjadi bagian-bagian kecil yang lebih mudah dikelola. Sebagai contoh, ketika tim pengembang ingin membuat aplikasi transportasi online, mereka tidak membangun semuanya sekaligus. Mereka memecahnya menjadi modul pendaftaran pengguna, sistem peta, pencocokan pengguna dengan pengemudi, sistem pembayaran, dan sistem penilaian.

### 2. Pengenalan Pola

Pengenalan pola adalah kemampuan menemukan kesamaan atau pola berulang dalam data. Sistem rekomendasi di TikTok dan YouTube menganalisis pola tontonan pengguna, lalu merekomendasikan konten serupa. Semakin lama digunakan, semakin akurat rekomendasinya karena sistem terus belajar dari pola perilaku baru.

### 3. Abstraksi

Abstraksi adalah fokus pada aspek penting dari suatu masalah sambil mengabaikan detail yang tidak relevan. Saat kita menggunakan aplikasi pesan, kita tidak perlu memahami bagaimana data dikirim melalui jaringan internet. Kita hanya perlu tahu cara mengetik dan mengirim. Inilah kekuatan abstraksi, menyembunyikan kompleksitas di balik layar.

### 4. Algoritma

Algoritma adalah urutan langkah yang jelas, terbatas, dan terurut untuk menyelesaikan masalah. Algoritma pencarian Google, algoritma rekomendasi Instagram, algoritma rute Google Maps, semuanya adalah hasil dari pemikiran komputasional yang matang. Bahkan algoritma yang mengatur lampu lalu lintas di persimpangan besar pun menggunakan prinsip yang sama.

## Penerapan AI Modern

### AI Generatif

Model AI generatif seperti ChatGPT, Gemini, dan Claude memperlihatkan betapa kuatnya berpikir komputasional ketika digabungkan dengan data besar dan komputasi cepat. Model ini dilatih dengan menganalisis pola dari miliaran teks, gambar, dan suara. Mereka belajar mengenali pola bahasa manusia, lalu menghasilkan teks baru yang masuk akal.

### Internet of Things

Internet of Things (IoT) menghubungkan perangkat fisik ke internet. Kulkas pintar yang dapat memesan susu sendiri, lampu yang menyala otomatis, dan smartwatch yang memantau detak jantung, semuanya bekerja dengan algoritma yang dibangun dari keempat pilar berpikir komputasional.

## Kesimpulan

Berpikir komputasional bukan sekadar keterampilan teknis untuk programmer. Ia adalah cara berpikir sistematis yang berguna di semua bidang kehidupan. Di era AI, kemampuan ini menjadi semakin penting karena manusia perlu mampu merancang, memahami, dan mengontrol sistem yang semakin cerdas. Kalian sebagai generasi muda Indonesia perlu membekali diri dengan kemampuan ini agar tidak hanya menjadi pengguna teknologi, tetapi juga pencipta solusi untuk masa depan yang lebih baik.`,

  // ---- Kelas 9B (laporan terstruktur dengan markdown) ----
  '9B': `# Laporan: Teknologi Masa Depan dan Peran Berpikir Komputasional

## Pendahuluan

Dunia sedang berubah dengan kecepatan yang belum pernah terjadi sebelumnya. Mobil yang dapat menyetir sendiri sudah menjalankan rute di kota-kota besar. Asisten AI dapat menulis esai, membuat gambar, bahkan menulis kode program dalam hitungan detik. Rumah-rumah pintar kini dapat mengontrol lampu, suhu, dan keamanan hanya dengan perintah suara. Di balik semua revolusi teknologi ini, ada satu kemampuan yang menjadi fondasi utama, yaitu berpikir komputasional.

## Konsep Berpikir Komputasional

Berpikir komputasional bukan sekadar kemampuan membuat program komputer. Lebih dari itu, berpikir komputasional adalah cara kita memecahkan masalah secara sistematis, logis, dan efisien. Ada empat pilar utama yang membentuk berpikir komputasional, dan setiap pilar saling melengkapi satu sama lain.

### Pilar 1: Dekomposisi

Dekomposisi adalah keterampilan memecah masalah besar yang kompleks menjadi sub-masalah yang lebih kecil dan mudah dikelola. Bayangkan sebuah tim yang ingin membangun aplikasi transportasi online seperti Gojek atau Grab. Mereka tidak membuat semuanya sekaligus, tetapi memecahnya menjadi modul pendaftaran pengguna, peta lokasi, pencocokan pengguna dengan pengemudi, sistem pembayaran, dan sistem rating. Setiap modul dikerjakan secara terpisah namun saling terhubung.

### Pilar 2: Pengenalan Pola

Pengenalan pola adalah kemampuan menemukan kesamaan atau pola berulang dalam data atau situasi yang berbeda. Sistem rekomendasi di TikTok atau YouTube adalah contoh nyata. Sistem ini menganalisis pola video yang kita tonton, durasi tontonan, dan pola interaksi kita, lalu merekomendasikan konten serupa yang kemungkinan besar akan kita sukai.

### Pilar 3: Abstraksi

Abstraksi adalah fokus pada aspek penting dari suatu masalah sambil mengabaikan detail yang tidak relevan. Saat kita menggunakan aplikasi pesan, kita tidak perlu memahami bagaimana data dikirimkan melalui jaringan internet atau bagaimana server memproses pesan kita. Kita hanya perlu tahu cara mengetik dan mengirim. Inilah kekuatan abstraksi, menyembunyikan kompleksitas agar pengguna mudah menggunakan teknologi.

### Pilar 4: Algoritma

Algoritma adalah urutan langkah yang jelas, terbatas, dan terurut untuk menyelesaikan masalah. Algoritma pencarian Google, algoritma pemberitaan Facebook, algoritma rute Google Maps, semua adalah hasil dari pemikiran komputasional yang matang. Bahkan algoritma yang mengatur lampu lalu lintas di persimpangan besar pun menggunakan prinsip yang sama.

## Tantangan dan Peluang di Era AI

### Peran Manusia di Tengah AI

Kehadiran AI generatif seperti ChatGPT, Gemini, dan Claude memperlihatkan betapa kuatnya berpikir komputasional ketika digabungkan dengan data yang sangat besar dan komputasi yang sangat cepat. Model AI ini dilatih dengan menganalisis pola dari miliaran teks, gambar, dan suara. Mereka belajar mengenali pola bahasa manusia, lalu menghasilkan teks baru yang masuk akal.

### AI Tidak Menggantikan Manusia

Namun perlu diingat, AI tidak menggantikan berpikir komputasional pada manusia. Justru sebaliknya, AI adalah produk dari berpikir komputasional. Manusialah yang merancang arsitektur AI, menentukan tujuan pelatihannya, dan menggunakan hasilnya untuk memecahkan masalah nyata.

## Kesimpulan

Berpikir komputasional menjadi keterampilan paling krusial bagi generasi kalian. Kalian akan hidup di dunia yang dipenuhi AI, robot, dan sistem otomatis. Yang akan membedakan kalian bukan kemampuan menghafal informasi, karena AI bisa melakukannya lebih cepat. Yang akan membedakan adalah kemampuan kalian memecahkan masalah secara sistematis, berpikir kritis, dan berkarya secara kreatif. Dengan berbekal berpikir komputasional, kalian bukan sekadar konsumen teknologi, tetapi menjadi penjelajah, pencipta, dan pemimpin di era digital ini.`,
}

// =====================================================
// SOAL HOTS — per tingkat kelas (8 = dasar, 9 = advanced)
// =====================================================

export const QUESTIONS_BY_GRADE: Record<'7' | '8' | '9', Question[]> = {
  // ===== KELAS 7: 30 soal dasar (komputer, internet, etika digital) =====
  '7': [
    { id: 1, question: 'Komputer adalah alat elektronik yang digunakan untuk...', options: ['Memasak makanan', 'Mengolah data menjadi informasi', 'Mencuci pakaian', 'Menanam pohon'], correctAnswer: 1, explanation: 'Komputer bekerja dengan menerima data, memprosesnya, lalu menghasilkan informasi yang berguna bagi pengguna.', category: 'Konsep Dasar' },
    { id: 2, question: 'Bagian komputer yang bisa kita lihat dan sentuh disebut...', options: ['Perangkat lunak', 'Perangkat keras', 'Sistem operasi', 'Aplikasi'], correctAnswer: 1, explanation: 'Perangkat keras (hardware) adalah bagian fisik komputer seperti monitor, keyboard, mouse, dan printer yang bisa dilihat dan disentuh.', category: 'Konsep Dasar' },
    { id: 3, question: 'Manakah yang termasuk perangkat keras komputer?', options: ['Microsoft Word', 'Windows', 'Keyboard', 'Google Chrome'], correctAnswer: 2, explanation: 'Keyboard adalah perangkat keras karena bentuknya fisik dan bisa disentuh. Microsoft Word, Windows, dan Chrome adalah perangkat lunak.', category: 'Konsep Dasar' },
    { id: 4, question: 'Fungsi monitor pada komputer adalah...', options: ['Mengetik huruf', 'Menggerakkan kursor', 'Menampilkan gambar dan tulisan', 'Mencetak dokumen'], correctAnswer: 2, explanation: 'Monitor adalah layar yang berfungsi menampilkan output visual seperti gambar, tulisan, dan video dari komputer.', category: 'Konsep Dasar' },
    { id: 5, question: 'Keyboard pada komputer berfungsi untuk...', options: ['Menampilkan gambar', 'Mengetik huruf dan angka', 'Mencetak dokumen', 'Menyimpan data'], correctAnswer: 1, explanation: 'Keyboard adalah alat input yang digunakan untuk mengetik huruf, angka, dan simbol ke dalam komputer.', category: 'Konsep Dasar' },
    { id: 6, question: 'Alat yang digunakan untuk menggerakkan kursor di layar komputer adalah...', options: ['Monitor', 'Printer', 'Mouse', 'Speaker'], correctAnswer: 2, explanation: 'Mouse adalah alat input yang digunakan untuk menggerakkan pointer/kursor dan memilih item di layar komputer.', category: 'Konsep Dasar' },
    { id: 7, question: 'Printer berfungsi untuk...', options: ['Menampilkan gambar di layar', 'Mencetak dokumen di atas kertas', 'Menyimpan file', 'Mengirim email'], correctAnswer: 1, explanation: 'Printer adalah perangkat output yang menghasilkan dokumen fisik berupa cetakan di atas kertas.', category: 'Konsep Dasar' },
    { id: 8, question: 'Program yang ada di dalam komputer dan tidak bisa disentuh disebut...', options: ['Perangkat keras', 'Perangkat lunak', 'Perangkat fisik', 'Perangkat eksternal'], correctAnswer: 1, explanation: 'Perangkat lunak (software) adalah program yang tidak berwujud fisik, seperti sistem operasi dan aplikasi.', category: 'Konsep Dasar' },
    { id: 9, question: 'Manakah yang termasuk perangkat lunak?', options: ['Monitor', 'Keyboard', 'Microsoft PowerPoint', 'Mouse'], correctAnswer: 2, explanation: 'Microsoft PowerPoint adalah aplikasi (perangkat lunak) yang digunakan untuk membuat presentasi.', category: 'Konsep Dasar' },
    { id: 10, question: 'Internet adalah jaringan yang menghubungkan...', options: ['Satu komputer', 'Beberapa teman', 'Jutaan komputer di seluruh dunia', 'Hanya komputer di sekolah'], correctAnswer: 2, explanation: 'Internet adalah jaringan global yang menghubungkan jutaan komputer di seluruh dunia sehingga bisa saling berkomunikasi dan berbagi informasi.', category: 'Internet' },
    { id: 11, question: 'Manakah BERIKUT yang BUKAN manfaat internet?', options: ['Mencari informasi', 'Berkomunikasi jarak jauh', 'Belajar online', 'Mencuri data orang lain'], correctAnswer: 3, explanation: 'Mencuri data orang lain adalah tindakan kriminal, bukan manfaat. Internet bermanfaat untuk mencari info, komunikasi, dan belajar.', category: 'Internet' },
    { id: 12, question: 'Informasi yang tidak benar dan menyesatkan di internet disebut...', options: ['Berita', 'Hoaks', 'Artikel', 'Jurnal'], correctAnswer: 1, explanation: 'Hoaks adalah informasi palsu atau menyesatkan yang disebarkan untuk menipu orang. Kita harus selalu cek kebenaran informasi sebelum percaya.', category: 'Internet' },
    { id: 13, question: 'Sebelum mempercayai informasi dari internet, kita harus...', options: ['Langsung membagikannya', 'Cek kebenaran sumbernya', 'Mempercayainya begitu saja', 'Mengabaikannya'], correctAnswer: 1, explanation: 'Kita harus selalu memverifikasi kebenaran informasi dari sumber tepercaya sebelum mempercayainya atau menyebarkannya.', category: 'Internet' },
    { id: 14, question: 'Etika bermedia digital yang baik adalah...', options: ['Menghina orang di media sosial', 'Menyebarkan berita bohong', 'Menggunakan bahasa sopan', 'Membagikan data pribadi orang'], correctAnswer: 2, explanation: 'Etika digital yang baik meliputi menggunakan bahasa sopan, menghormati privasi, dan tidak menyebarkan informasi palsu.', category: 'Etika Digital' },
    { id: 15, question: 'Saat berkomunikasi di internet, kita harus menggunakan...', options: ['Bahasa kasar', 'Bahasa sopan', 'Bahasa daerah saja', 'Bahasa asing'], correctAnswer: 1, explanation: 'Etika digital menuntut kita menggunakan bahasa yang sopan dan menghormati orang lain saat berkomunikasi online.', category: 'Etika Digital' },
    { id: 16, question: 'Membagikan foto teman tanpa izin merupakan pelanggaran terhadap...', options: ['Hak cipta', 'Privasi', 'Hukum dagang', 'Aturan sekolah saja'], correctAnswer: 1, explanation: 'Setiap orang memiliki hak privasi. Membagikan foto atau informasi pribadi orang lain tanpa izin adalah pelanggaran etika digital.', category: 'Etika Digital' },
    { id: 17, question: 'Menyalin pekerjaan orang lain tanpa menyebut sumbernya disebut...', options: ['Berbagi', 'Plagiarisme', 'Kolaborasi', 'Kutipan'], correctAnswer: 1, explanation: 'Plagiarisme adalah menyalin karya orang lain tanpa izin atau menyebut sumbernya. Ini melanggar hak cipta dan etika.', category: 'Etika Digital' },
    { id: 18, question: 'Password yang baik harus...', options: ['Mudah ditebak', 'Pendek saja', 'Kuat dan tidak dibagikan ke siapapun', 'Sama dengan nama'], correctAnswer: 2, explanation: 'Password yang kuat terdiri dari kombinasi huruf, angka, dan simbol. Jangan pernah membagikannya kepada siapapun.', category: 'Keamanan Digital' },
    { id: 19, question: 'Jika menerima pesan menawarkan hadiah gratis dari orang tidak dikenal, kita harus...', options: ['Langsung membalas', 'Berikan data pribadi', 'Mengabaikannya dan waspada', 'Bagikan ke teman'], correctAnswer: 2, explanation: 'Pesan hadiah gratis dari orang tidak dikenal biasanya penipuan. Kita harus mengabaikannya dan tidak memberikan data pribadi.', category: 'Keamanan Digital' },
    { id: 20, question: 'Data berikut yang TIDAK boleh dibagikan ke orang asing di internet adalah...', options: ['Nama panggilan', 'Hobi', 'Alamat rumah dan nomor rekening', 'Warna favorit'], correctAnswer: 2, explanation: 'Data sensitif seperti alamat rumah, nomor rekening, dan password tidak boleh dibagikan ke orang yang tidak dikenal karena berisiko ditipu.', category: 'Keamanan Digital' },
    { id: 21, question: 'Terlalu lama bermain ponsel dapat menyebabkan...', options: ['Mata menjadi lebih sehat', 'Nilai pelajaran menurun', 'Tubuh lebih bugar', 'Lebih banyak teman'], correctAnswer: 1, explanation: 'Kecanduan ponsel dapat membuat kita lupa waktu, mengabaikan tugas sekolah, sehingga nilai menurun dan kesehatan terganggu.', category: 'Kesehatan Digital' },
    { id: 22, question: 'Tips menggunakan ponsel dengan bijak adalah...', options: ['Gunakan seharian penuh', 'Main saat belajar', 'Tentukan batas waktu penggunaan', 'Main saat makan'], correctAnswer: 2, explanation: 'Kita perlu menentukan batas waktu penggunaan ponsel, misalnya maksimal 2 jam per hari, agar tidak lupa waktu dan tetap produktif.', category: 'Kesehatan Digital' },
    { id: 23, question: 'Sebaiknya ponsel dimatikan saat...', options: ['Makan bersama keluarga dan saat tidur', 'Bermain di taman', 'Berjalan-jalan', 'Belajar di perpustakaan sendiri'], correctAnswer: 0, explanation: 'Matikan ponsel saat makan bersama keluarga agar bisa interaksi langsung, dan saat tidur agar tidak terganggu notifikasi.', category: 'Kesehatan Digital' },
    { id: 24, question: 'Perkembangan teknologi komputer dari masa ke masa menunjukkan bahwa...', options: ['Komputer semakin besar dan berat', 'Komputer semakin kecil dan canggih', 'Komputer tidak berubah', 'Komputer semakin mahal saja'], correctAnswer: 1, explanation: 'Dulu komputer berukuran besar, sekarang menjadi kecil dan canggih seperti ponsel pintar yang bisa disimpan di saku.', category: 'Konsep Dasar' },
    { id: 25, question: 'Ponsel pintar termasuk perkembangan dari...', options: ['Komputer', 'Televisi', 'Radio', 'Mesin tik'], correctAnswer: 0, explanation: 'Ponsel pintar pada dasarnya adalah komputer kecil yang bisa disimpan di saku, dengan kemampuan komunikasi dan komputasi.', category: 'Konsep Dasar' },
    { id: 26, question: 'Saatsedang belajar, sebaiknya kita...', options: ['Buka media sosial', 'Main game', 'Fokus dan jauhi gangguan ponsel', 'Tonton film'], correctAnswer: 2, explanation: 'Saat belajar, kita harus fokus. Jauhi gangguan dari ponsel seperti media sosial atau game agar proses belajar efektif.', category: 'Kesehatan Digital' },
    { id: 27, question: 'Jika ada orang tidak dikenal mengirim pesan mencurigakan, langkah yang benar adalah...', options: ['Balas ramah', 'Beritahu orang tua atau guru', 'Berikan nomor rekening', 'Undang bertemu'], correctAnswer: 1, explanation: 'Pesan mencurigakan bisa jadi penipuan. Segera beritahu orang tua atau guru agar mereka bisa membantu menanganinya.', category: 'Keamanan Digital' },
    { id: 28, question: 'Media sosial sebaiknya digunakan untuk...', options: ['Menghina orang lain', 'Menyebarkan gosip', 'Berbagi hal positif dan bermanfaat', 'Mencuri akun orang'], correctAnswer: 2, explanation: 'Media sosial sebaiknya digunakan untuk hal positif seperti berbagi pengetahuan, inspirasi, dan menjaga silaturahmi, bukan untuk merugikan orang lain.', category: 'Etika Digital' },
    { id: 29, question: 'Mengapa kita harus pintar memilih sumber informasi di internet?', options: ['Karena semua informasi di internet benar', 'Karena banyak informasi palsu atau hoaks', 'Karena internet tidak berguna', 'Karena internet mahal'], correctAnswer: 1, explanation: 'Tidak semua informasi di internet benar. Banyak hoaks dan informasi menyesatkan, jadi kita harus cek sumbernya dengan teliti.', category: 'Internet' },
    { id: 30, question: 'Generasi muda sebagai penerus bangsa sebaiknya menggunakan teknologi untuk...', options: ['Hal-hal yang merugikan', 'Kemajuan diri dan orang banyak', 'Bermain game terus', 'Menghindari belajar'], correctAnswer: 1, explanation: 'Teknologi harus dimanfaatkan untuk hal positif seperti belajar, berkarya, dan memajukan diri serta memberi manfaat bagi orang banyak.', category: 'Etika Digital' },
  ],

  // ===== KELAS 8: 30 soal dasar berpikir komputasional =====
  '8': [
    { id: 1, question: 'Ketika ibu memasak nasi, urutan langkahnya adalah: cuci beras, masukkan air, tekan tombol cook. Urutan langkah ini merupakan contoh penerapan...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 3, explanation: 'Algoritma adalah urutan langkah yang jelas dan berurutan untuk menyelesaikan suatu tugas. Cara memasak nasi adalah contoh algoritma sehari-hari.', category: 'Algoritma' },
    { id: 2, question: 'Seorang siswa mendapat tugas membuat poster hari kemerdekaan. Ia memecah tugas menjadi: tentukan tema, cari referensi, buat sketsa, warnai, tambah tulisan. Pendekatan ini disebut...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 0, explanation: 'Dekomposisi adalah memecah masalah besar menjadi bagian-bagian kecil yang lebih mudah dikerjakan.', category: 'Dekomposisi' },
    { id: 3, question: 'Pada jadwal pelajaran, hanya ditampilkan nama mapel, jam, dan nama guru. Tidak ada gambar wajah guru atau warna bajunya. Hal ini menunjukkan konsep...', options: ['Dekomposisi', 'Abstraksi', 'Algoritma', 'Pengenalan pola'], correctAnswer: 1, explanation: 'Abstraksi berarti fokus pada informasi penting dan mengabaikan detail yang tidak relevan.', category: 'Abstraksi' },
    { id: 4, question: 'Seorang siswa melihat deretan bilangan: 2, 4, 6, 8, ... Ia menyimpulkan angka berikutnya adalah 10. Keterampilan berpikir komputasional yang digunakan adalah...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 1, explanation: 'Siswa mengenali pola bilangan genap yang bertambah 2 setiap langkah.', category: 'Pengenalan Pola' },
    { id: 5, question: 'Berikut adalah langkah membuat origami burung: (1) lipat kertas menjadi segitiga, (2) lipat lagi menjadi lebih kecil, (3) bentuk sayap, (4) bentuk ekor. Langkah-langkah ini merupakan contoh...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 3, explanation: 'Langkah membuat origami adalah algoritma karena berupa urutan instruksi yang jelas, terurut, dan terbatas.', category: 'Algoritma' },
    { id: 6, question: 'Ketika menggunakan aplikasi WhatsApp, urutannya adalah: buka aplikasi, pilih kontak, ketik pesan, tekan kirim. Konsep berpikir komputasional yang diilustrasikan adalah...', options: ['Algoritma', 'Abstraksi', 'Dekomposisi', 'Pengenalan pola'], correctAnswer: 0, explanation: 'Urutan langkah yang harus diikuti untuk mengirim pesan adalah algoritma.', category: 'Algoritma' },
    { id: 7, question: 'Saat membuat peta sekolah, kalian hanya menggambar ruang kelas, lapangan, toilet, dan kantin. Tidak menggambar setiap pohon atau detail kecil lain. Hal ini menunjukkan...', options: ['Abstraksi', 'Algoritma', 'Dekomposisi', 'Pengenalan pola'], correctAnswer: 0, explanation: 'Peta sekolah fokus pada informasi penting untuk navigasi dan mengabaikan detail yang tidak relevan.', category: 'Abstraksi' },
    { id: 8, question: 'Seorang siswa mengadakan pesta ulang tahun. Ia memecah tugas menjadi: tentukan tema, buat daftar tamu, siapkan makanan, susun acara. Pendekatan ini disebut...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 0, explanation: 'Memecah perencanaan pesta menjadi beberapa sub-tugas yang lebih kecil adalah dekomposisi.', category: 'Dekomposisi' },
    { id: 9, question: 'Siswa memperhatikan bahwa nilai ulangannya lebih baik ketika ia belajar malam sebelumnya. Ia menyimpulkan pola "belajar malam = nilai bagus". Keterampilan yang digunakan adalah...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 1, explanation: 'Siswa mengenali pola hubungan antara kebiasaan belajar malam dan nilai ulangan.', category: 'Pengenalan Pola' },
    { id: 10, question: 'Manakah yang BUKAN merupakan ciri algoritma yang baik?', options: ['Langkahnya jelas dan tidak ambigu', 'Jumlah langkahnya terbatas', 'Hasilnya bisa berbeda untuk input yang sama', 'Memiliki urutan awal dan akhir'], correctAnswer: 2, explanation: 'Algoritma yang baik harus deterministik: untuk input yang sama, hasilnya harus selalu sama.', category: 'Algoritma' },
    { id: 11, question: 'Saat belajar bahasa Inggris, siswa memperhatikan bahwa kata berakhiran -ly biasanya adalah keterangan (adverb). Ia menggunakan pola ini untuk memahami kalimat baru. Keterampilan yang digunakan adalah...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 1, explanation: 'Siswa mengenali pola akhiran -ly sebagai penanda adverb.', category: 'Pengenalan Pola' },
    { id: 12, question: 'Membuat akun media sosial dengan urutan: unduh aplikasi, isi data, buat username dan password, verifikasi. Konsep berpikir komputasional yang tergambar adalah...', options: ['Algoritma', 'Abstraksi', 'Dekomposisi', 'Pengenalan pola'], correctAnswer: 0, explanation: 'Urutan langkah jelas untuk membuat akun adalah algoritma.', category: 'Algoritma' },
    { id: 13, question: 'Ketika menonton video pembelajaran, siswa hanya mencatat isi materi dan tidak mengingat warna baju presenter. Hal ini menunjukkan penerapan...', options: ['Abstraksi', 'Algoritma', 'Dekomposisi', 'Pengenalan pola'], correctAnswer: 0, explanation: 'Siswa fokus pada informasi penting (isi materi) dan mengabaikan detail yang tidak relevan.', category: 'Abstraksi' },
    { id: 14, question: 'Untuk membuat presentasi kelompok, siswa membagi tugas: Ali cari informasi, Budi buat slide, Cici susun naskah, Doni latihan presentasi. Pendekatan ini disebut...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 0, explanation: 'Memecah tugas presentasi menjadi sub-tugas yang dikerjakan tiap anggota adalah dekomposisi.', category: 'Dekomposisi' },
    { id: 15, question: 'Seorang siswa menyusun jadwal belajar harian: jam 16.00 mengerjakan PR, jam 18.00 belajar materi baru, jam 19.30 makan, jam 20.00 ulang baca. Susunan ini merupakan contoh...', options: ['Algoritma', 'Dekomposisi', 'Pengenalan pola', 'Abstraksi'], correctAnswer: 0, explanation: 'Jadwal belajar dengan urutan waktu yang jelas adalah algoritma.', category: 'Algoritma' },
    { id: 16, question: 'Aplikasi transportasi online seperti Gojek dapat mencari pengemudi terdekat. Di balik layar, aplikasi menggunakan urutan langkah sistematis untuk menemukan pengemudi. Konsep yang digunakan adalah...', options: ['Algoritma pencarian', 'Abstraksi warna motor', 'Dekomposisi penumpang', 'Pengenalan pola baju'], correctAnswer: 0, explanation: 'Aplikasi menggunakan algoritma pencarian untuk menemukan pengemudi terdekat berdasarkan lokasi GPS.', category: 'Algoritma' },
    { id: 17, question: 'Saat bermain game puzzle, pemain harus memikirkan langkah mana yang diambil lebih dulu dan mengenali pola musuh yang muncul. Keterampilan berpikir komputasional yang TIDAK terlibat dalam aktivitas ini adalah...', options: ['Pengenalan pola musuh', 'Algoritma langkah', 'Abstraksi fokus tujuan', 'Dekomposisi warna layar'], correctAnswer: 3, explanation: 'Warna layar bukan informasi penting dalam menyelesaikan puzzle.', category: 'Konsep Dasar' },
    { id: 18, question: 'Pada peta Indonesia, hanya digambar pulau-pulau besar, batas provinsi, dan nama kota besar. Tidak digambar setiap rumah atau jalan kecil. Hal ini menunjukkan...', options: ['Abstraksi', 'Algoritma', 'Dekomposisi', 'Pengenalan pola'], correctAnswer: 0, explanation: 'Peta hanya menampilkan informasi penting untuk navigasi geografis.', category: 'Abstraksi' },
    { id: 19, question: 'Seorang siswa ingin membersihkan kamarnya yang berantakan. Ia mulai dengan memilah mainan, lalu buku, lalu pakaian, terakhir sampah. Pendekatan ini menunjukkan...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 0, explanation: 'Memilah pekerjaan membersihkan kamar berdasarkan kategori adalah dekomposisi.', category: 'Dekomposisi' },
    { id: 20, question: 'Saat berbelanja di minimarket, kasir memindai barang satu per satu, lalu sistem menjumlahkan harga, dan menampilkan total bayar. Proses ini menggunakan...', options: ['Algoritma perhitungan', 'Abstraksi warna kemasan', 'Dekomposisi kasir', 'Pengenalan pola pelanggan'], correctAnswer: 0, explanation: 'Sistem kasir menggunakan algoritma: pindai barang, jumlahkan harga, tampilkan total.', category: 'Algoritma' },
    { id: 21, question: 'Seorang siswa memperhatikan bahwa teman-temannya yang rajin membaca memiliki kosakata yang lebih banyak. Ia menyimpulkan "rajin membaca = kosakata banyak". Kesimpulan ini merupakan hasil dari...', options: ['Pengenalan pola', 'Dekomposisi', 'Abstraksi', 'Algoritma'], correctAnswer: 0, explanation: 'Siswa mengenali pola hubungan antara kebiasaan membaca dan jumlah kosakata.', category: 'Pengenalan Pola' },
    { id: 22, question: 'Resep membuat telur dadar: kocok telur, panaskan minyak, tuang telur, tunggu matang, angkat. Resep ini adalah contoh algoritma karena...', options: ['Langkahnya harus urut, jelas, dan terbatas untuk menghasilkan telur dadar', 'Resep bisa diubah-ubah urutannya', 'Resep tidak perlu diikuti', 'Resep hanya untuk chef profesional'], correctAnswer: 0, explanation: 'Algoritma harus memiliki urutan langkah yang jelas, terbatas, dan harus diikuti.', category: 'Algoritma' },
    { id: 23, question: 'Saat membuat denah rumah, arsitek hanya menggambar dinding, pintu, dan jendela, tanpa menggambar kabel atau pipa di dalam dinding. Konsep berpikir komputasional yang digunakan adalah...', options: ['Abstraksi', 'Algoritma', 'Dekomposisi', 'Pengenalan pola'], correctAnswer: 0, explanation: 'Denah rumah fokus pada tata letak penting dan mengabaikan detail yang tidak relevan.', category: 'Abstraksi' },
    { id: 24, question: 'Seorang siswa diminta menjelaskan cara membuat sandwich kepada adiknya. Penjelasan yang sesuai prinsip algoritma adalah...', options: ['Buat sandwich sesuka hatimu', 'Ambil dua lembar roti, olesi selai kacang pada satu lembar, olesi selai stroberi pada lembar lain, tutup keduanya, potong jadi dua segitiga', 'Sandwich itu enak dan mudah dibuat', 'Beli sandwich di toko terdekat'], correctAnswer: 1, explanation: 'Algoritma harus jelas, terurut, dan tidak ambigu.', category: 'Algoritma' },
    { id: 25, question: 'Aplikasi game mobile legend memiliki urutan: buka aplikasi, login, pilih mode, pilih hero, mulai bertanding. Konsep berpikir komputasional yang terlihat adalah...', options: ['Algoritma', 'Abstraksi', 'Dekomposisi', 'Pengenalan pola'], correctAnswer: 0, explanation: 'Urutan langkah untuk memulai permainan adalah algoritma.', category: 'Algoritma' },
    { id: 26, question: 'Manakah dari berikut yang merupakan contoh dekomposisi dalam kehidupan sehari-hari?', options: ['Mengenali bahwa hujan selalu diikuti pelangi', 'Membagi tugas membersihkan rumah: sapu lantai, cuci piring, lipat baju', 'Membuat peta yang hanya menampilkan jalan utama', 'Mengikuti resep masakan langkah demi langkah'], correctAnswer: 1, explanation: 'Memecah tugas membersihkan rumah menjadi tiga sub-tugas spesifik adalah dekomposisi.', category: 'Dekomposisi' },
    { id: 27, question: 'Aplikasi musik seperti Spotify menampilkan playlist "Lagu Populer" berdasarkan lagu yang sering diputar pengguna lain. Hal ini menggunakan konsep...', options: ['Pengenalan pola pendengaran pengguna', 'Dekomposisi lagu', 'Abstraksi lirik', 'Algoritma penghapusan data'], correctAnswer: 0, explanation: 'Spotify menganalisis pola pendengaran jutaan pengguna untuk merekomendasikan lagu populer.', category: 'Pengenalan Pola' },
    { id: 28, question: 'Mengapa berpikir komputasional penting dipelajari sejak SMP, meskipun tidak semua siswa akan menjadi programmer?', options: ['Karena berpikir komputasional hanya berguna untuk membuat aplikasi', 'Karena berpikir komputasional melatih cara memecahkan masalah secara sistematis yang berguna di semua bidang kehidupan', 'Karena semua pekerjaan masa depan wajib menggunakan komputer', 'Karena berpikir komputasional hanya untuk pelajaran informatika'], correctAnswer: 1, explanation: 'Berpikir komputasional bukan hanya soal coding, tetapi tentang cara berpikir sistematis untuk memecahkan masalah.', category: 'Konsep Dasar' },
    { id: 29, question: 'Seorang siswa ingin menyelesaikan PR matematika yang banyak. Strategi terbaik dengan prinsip dekomposisi adalah...', options: ['Mengerjakan semuanya dalam satu malam tanpa istirahat', 'Memilah PR berdasarkan topik, mengerjakan yang mudah dulu, lalu yang sulit', 'Menunda sampai terakhir menit', 'Meminta teman mengerjakan'], correctAnswer: 1, explanation: 'Dekomposisi mengajak kita memecah masalah besar menjadi bagian kecil.', category: 'Dekomposisi' },
    { id: 30, question: 'Manakah pernyataan yang PALING TEPAT tentang hubungan berpikir komputasional dengan teknologi yang kita gunakan sehari-hari?', options: ['Berpikir komputasional hanya digunakan oleh ilmuwan komputer', 'Semua aplikasi dan teknologi modern dibangun dengan prinsip berpikir komputasional, dan kita pun bisa menerapkannya dalam kehidupan', 'Berpikir komputasional tidak berkaitan dengan teknologi', 'Berpikir komputasional hanya untuk siswa SMA'], correctAnswer: 1, explanation: 'Setiap teknologi yang kita gunakan dibangun dengan empat pilar berpikir komputasional.', category: 'Konsep Dasar' },
  ],
  '9': [
    { id: 1, question: 'Seorang siswa ingin membuat aplikasi absensi digital untuk sekolahnya. Langkah pertama yang sebaiknya ia lakukan sesuai prinsip berpikir komputasional adalah...', options: ['Langsung menulis kode program tanpa perencanaan', 'Memecah masalah menjadi fitur-fitur kecil seperti login, input absensi, dan rekapitulasi', 'Membeli komputer dengan spesifikasi paling tinggi', 'Menanyakan ke teman apakah aplikasi ini bagus atau tidak'], correctAnswer: 1, explanation: 'Dekomposisi adalah pilar pertama yang mengharuskan kita memecah masalah besar menjadi bagian-bagian kecil.', category: 'Dekomposisi' },
    { id: 2, question: 'Pada aplikasi streaming musik, sistem sering menampilkan playlist "Mungkin Kamu Suka". Kemampuan berpikir komputasional yang paling tepat digunakan sistem adalah...', options: ['Abstraksi', 'Algoritma', 'Pengenalan pola', 'Dekomposisi'], correctAnswer: 2, explanation: 'Sistem merekomendasikan musik berdasarkan kesamaan pola lagu yang sering kita dengar.', category: 'Pengenalan Pola' },
    { id: 3, question: 'Peta jaringan kereta bawah tanah hanya menampilkan garis warna-warni dan nama stasiun, tanpa menggambar detail bangunan atau jalan kecil. Konsep yang diilustrasikan adalah...', options: ['Dekomposisi', 'Abstraksi', 'Algoritma', 'Pengenalan pola'], correctAnswer: 1, explanation: 'Abstraksi berarti fokus pada informasi penting dan mengabaikan detail yang tidak relevan.', category: 'Abstraksi' },
    { id: 4, question: 'Berikut adalah langkah membuat mie instan: (1) rebus air, (2) masukkan mie, (3) tunggu 3 menit, (4) campur bumbu, (5) sajikan. Urutan langkah ini merupakan contoh penerapan...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 3, explanation: 'Algoritma adalah urutan langkah yang jelas, terbatas, dan berurutan.', category: 'Algoritma' },
    { id: 5, question: 'Mobil otonom (self-driving car) menggunakan kamera dan sensor untuk mendeteksi kendaraan lain, pejalan kaki, dan rambu lalu lintas. Saat mobil harus memutuskan mengerem atau menambah kecepatan, pilar yang paling banyak diandalkan adalah...', options: ['Algoritma', 'Abstraksi', 'Pengenalan pola', 'Dekomposisi'], correctAnswer: 0, explanation: 'Keputusan mengerem atau menambah kecepatan memerlukan algoritma pengambilan keputusan real-time.', category: 'Algoritma' },
    { id: 6, question: 'Ketika seorang programmer ingin membuat game RPG yang besar, ia mulai dengan membuat modul cerita, lalu modul karakter, modul pertarungan, dan modul inventaris. Pendekatan ini menunjukkan penerapan...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 0, explanation: 'Memecah game besar menjadi modul-modul yang lebih kecil adalah dekomposisi.', category: 'Dekomposisi' },
    { id: 7, question: 'Seorang siswa memperhatikan bahwa setiap kali ia lupa mengerjakan PR, ia mendapat nilai rendah. Dari pengamatan ini, ia menyimpulkan pola "lupa PR = nilai rendah". Keterampilan yang digunakan adalah...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 1, explanation: 'Siswa mengenali pola berulang antara "lupa PR" dan "nilai rendah".', category: 'Pengenalan Pola' },
    { id: 8, question: 'Pada peta digital seperti Google Maps, kita bisa mencari rute tercepat ke sekolah. Peta tidak menampilkan setiap rumah atau pohon, hanya jalan utama dan lokasi penting. Hal ini menunjukkan konsep...', options: ['Abstraksi', 'Algoritma', 'Dekomposisi', 'Pengenalan pola'], correctAnswer: 0, explanation: 'Peta digital hanya menampilkan informasi penting dan mengabaikan detail yang tidak relevan.', category: 'Abstraksi' },
    { id: 9, question: 'Algoritma pengurutan angka dari terkecil ke terbesar dapat digunakan untuk mengurutkan nilai ulangan, tinggi badan pemain basket, harga barang, dan jadwal kedatangan kereta. Pernyataan yang paling tepat adalah...', options: ['Algoritma hanya cocok untuk angka saja', 'Algoritma yang sama dapat digunakan untuk semua situasi tersebut karena masalahnya memiliki pola yang serupa', 'Setiap masalah memerlukan algoritma yang berbeda total', 'Algoritma pengurutan tidak dapat diterapkan pada masalah nyata'], correctAnswer: 1, explanation: 'Pengenalan pola memungkinkan kita menggunakan algoritma yang sama untuk berbagai masalah dengan struktur serupa.', category: 'Pengenalan Pola' },
    { id: 10, question: 'Ketika menghadapi masalah besar seperti "mengurangi sampah plastik di sekolah", berpikir komputasional menyarankan kita untuk...', options: ['Mencoba menyelesaikan semuanya dalam satu hari', 'Memecah masalah menjadi sub-masalah: jenis sampah, sumber sampah, solusi daur ulang, dan sosialisasi', 'Menunggu pemerintah menyelesaikannya', 'Membuang semua sampah ke satu tempat saja'], correctAnswer: 1, explanation: 'Dekomposisi mengajak kita memecah masalah besar menjadi sub-masalah yang lebih kecil.', category: 'Dekomposisi' },
    { id: 11, question: 'Seorang siswa membuat flowchart untuk menentukan apakah suatu bilangan genap atau ganjil. Flowchart ini adalah representasi visual dari...', options: ['Abstraksi', 'Dekomposisi', 'Algoritma', 'Pengenalan pola'], correctAnswer: 2, explanation: 'Flowchart adalah representasi visual dari algoritma.', category: 'Algoritma' },
    { id: 12, question: 'Dalam desain antarmuka aplikasi, tombol "Simpan" biasanya berwarna hijau dan tombol "Hapus" berwarna merah. Pengguna sudah terbiasa dengan pola ini. Penerapan konsep berpikir komputasional pada desain ini adalah...', options: ['Algoritma', 'Pengenalan pola', 'Dekomposisi', 'Abstraksi'], correctAnswer: 1, explanation: 'Desainer menggunakan pola warna yang sudah dikenali pengguna agar antarmuka lebih intuitif.', category: 'Pengenalan Pola' },
    { id: 13, question: 'Saat kita menggunakan aplikasi pesan makanan, kita tidak perlu memahami bagaimana server bekerja, bagaimana pembayaran diproses, atau bagaimana kurir ditugaskan. Kita hanya perlu memilih makanan dan alamat. Hal ini menunjukkan konsep...', options: ['Abstraksi', 'Dekomposisi', 'Pengenalan pola', 'Algoritma'], correctAnswer: 0, explanation: 'Aplikasi menyembunyikan kompleksitas di balik layar dan hanya menampilkan fungsi penting.', category: 'Abstraksi' },
    { id: 14, question: 'Manakah dari berikut yang BUKAN merupakan karakteristik algoritma yang baik?', options: ['Langkah-langkahnya harus jelas dan tidak ambigu', 'Jumlah langkahnya terbatas', 'Bisa memberikan hasil yang berbeda untuk input yang sama', 'Memiliki titik awal dan titik akhir'], correctAnswer: 2, explanation: 'Algoritma yang baik harus deterministik.', category: 'Algoritma' },
    { id: 15, question: 'Seorang guru ingin membagi 30 siswa ke dalam kelompok berisi 5 orang. Langkah sistematis yang merupakan algoritma adalah...', options: ['Membagi siswa secara acak dan berharap hasilnya pas', 'Mengurutkan siswa berdasarkan abjad nama, lalu mengelompokkan 5 siswa pertama, 5 siswa berikutnya, dan seterusnya', 'Meminta siswa memilih kelompoknya sendiri', 'Membagi siswa berdasarkan teman dekat saja'], correctAnswer: 1, explanation: 'Algoritma harus jelas, terurut, dan dapat diprediksi hasilnya.', category: 'Algoritma' },
    { id: 16, question: 'Internet of Things (IoT) memungkinkan perangkat seperti lampu, kulkas, dan AC terhubung ke internet. Ketika kulkas pintar bisa memperingatkan bahwa susu akan habis, pilar yang paling dominan adalah...', options: ['Algoritma monitoring dan pengambilan keputusan otomatis', 'Abstraksi visual antarmuka', 'Dekomposisi susu menjadi molekul', 'Pengenalan pola warna kemasan susu'], correctAnswer: 0, explanation: 'Kulkas pintar menggunakan algoritma untuk memantau stok dan memutuskan kapan harus memperingatkan pengguna.', category: 'Algoritma' },
    { id: 17, question: 'Aplikasi e-commerce seperti Tokopedia atau Shopee dapat menampilkan produk "Yang Mungkin Kamu Sukai" berdasarkan riwayat pencarian dan pembelian. Hal ini memanfaatkan teknologi AI yang bekerja dengan prinsip...', options: ['Dekomposisi produk', 'Pengenalan pola perilaku pengguna', 'Abstraksi harga produk', 'Algoritma penghapusan data'], correctAnswer: 1, explanation: 'Sistem AI menganalisis pola perilaku pengguna untuk merekomendasikan produk serupa.', category: 'Pengenalan Pola' },
    { id: 18, question: 'Berikut adalah langkah mencuci pakaian dengan mesin cuci: (1) pisahkan pakaian putih dan berwarna, (2) masukkan pakaian ke mesin, (3) tambahkan deterjen, (4) pilih program cuci, (5) jalankan mesin, (6) jemur pakaian. Pemisahan pakaian putih dan berwarna pada langkah (1) merupakan bentuk...', options: ['Abstraksi', 'Dekomposisi', 'Pengenalan pola', 'Algoritma acak'], correctAnswer: 1, explanation: 'Memisahkan pakaian berdasarkan warna adalah contoh dekomposisi.', category: 'Dekomposisi' },
    { id: 19, question: 'Dalam pembuatan aplikasi, seorang programmer sering menggunakan "fungsi" untuk tugas berulang seperti menghitung total belanja. Alih-alih menulis kode yang sama berkali-kali, ia cukup memanggil fungsi tersebut. Konsep yang paling tepat adalah...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 1, explanation: 'Programmer mengenali pola perhitungan yang berulang, lalu membuat fungsi reusable.', category: 'Pengenalan Pola' },
    { id: 20, question: 'Seorang siswa diminta membuat daftar belanja untuk pesta ulang tahun. Ia membuat daftar kategori: makanan, minuman, peralatan, dan dekorasi. Pendekatan ini menunjukkan penerapan...', options: ['Dekomposisi', 'Pengenalan pola', 'Abstraksi', 'Algoritma'], correctAnswer: 0, explanation: 'Memecah daftar belanja berdasarkan kategori adalah dekomposisi.', category: 'Dekomposisi' },
    { id: 21, question: 'Pada sistem keamanan berbasis pengenalan wajah (face recognition), ponsel dapat membuka kunci hanya dengan melihat wajah pemiliknya. Teknologi ini menggunakan pilar berpikir komputasional dalam bentuk...', options: ['Pengenalan pola wajah', 'Dekomposisi wajah', 'Abstraksi password', 'Algoritma penghapusan data'], correctAnswer: 0, explanation: 'Sistem mempelajari pola fitur wajah untuk membedakan pemilik dengan orang lain.', category: 'Pengenalan Pola' },
    { id: 22, question: 'Manakah pernyataan berikut yang PALING TEPAT tentang hubungan antara kecerdasan buatan (AI) dan berpikir komputasional?', options: ['AI menggantikan kebutuhan berpikir komputasional pada manusia', 'AI dibangun di atas dasar berpikir komputasional seperti dekomposisi, pengenalan pola, abstraksi, dan algoritma', 'AI dan berpikir komputasional adalah dua hal yang tidak berkaitan', 'Berpikir komputasional hanya digunakan untuk membuat AI, bukan untuk hal lain'], correctAnswer: 1, explanation: 'AI dibangun dengan menerapkan keempat pilar berpikir komputasional.', category: 'Konsep Dasar' },
    { id: 23, question: 'Seorang siswa diminta menjelaskan cara membuat sandwich kepada temannya yang belum pernah memasak. Penjelasan yang paling sesuai dengan prinsip algoritma adalah...', options: ['Buat sandwich sesuai perasaanmu', 'Ambil dua lembar roti, olesi selai kacang pada satu lembar, olesi selai stroberi pada lembar lainnya, tutup keduanya, lalu potong menjadi dua segitiga', 'Sandwich itu makanan enak', 'Beli sandwich di toko terdekat'], correctAnswer: 1, explanation: 'Algoritma harus jelas, terurut, dan tidak ambigu.', category: 'Algoritma' },
    { id: 24, question: 'Ketika seorang arsitek membuat denah rumah, ia hanya menggambar dinding, pintu, dan jendela tanpa menggambar setiap baut atau kabel di dalam dinding. Konsep yang digunakan adalah...', options: ['Abstraksi', 'Algoritma', 'Dekomposisi', 'Pengenalan pola'], correctAnswer: 0, explanation: 'Denah rumah fokus pada informasi penting dan mengabaikan detail yang tidak relevan.', category: 'Abstraksi' },
    { id: 25, question: 'Aplikasi peta digital seperti Google Maps dapat menemukan rute tercepat ke suatu tujuan dengan mempertimbangkan jarak, kondisi lalu lintas, dan jalan tertutup. Di balik layar, aplikasi menggunakan...', options: ['Algoritma pencarian rute yang kompleks', 'Abstraksi seluruh kota', 'Dekomposisi setiap kendaraan', 'Pengenalan pola warna mobil'], correctAnswer: 0, explanation: 'Aplikasi peta menggunakan algoritma pencarian jalur seperti Dijkstra atau A*.', category: 'Algoritma' },
    { id: 26, question: 'Seorang siswa menganalisis data nilai ulangan kelasnya dan menemukan bahwa nilai matematika cenderung turun ketika siswa kurang tidur malam sebelumnya. Temuan ini merupakan hasil dari...', options: ['Pengenalan pola antara kebiasaan tidur dan prestasi belajar', 'Dekomposisi data nilai', 'Abstraksi matematika', 'Algoritma penghitungan nilai'], correctAnswer: 0, explanation: 'Siswa mengenali pola hubungan antara durasi tidur dan nilai matematika.', category: 'Pengenalan Pola' },
    { id: 27, question: 'Pada sebuah toko online, proses checkout terdiri dari: pilih barang -> masukkan keranjang -> isi alamat -> pilih pengiriman -> pilih pembayaran -> konfirmasi pesanan. Urutan ini tidak boleh diacak. Hal ini menunjukkan pentingnya...', options: ['Algoritma yang berurutan', 'Abstraksi produk', 'Dekomposisi pelanggan', 'Pengenalan pola harga'], correctAnswer: 0, explanation: 'Urutan langkah checkout yang harus diikuti secara berurutan adalah algoritma.', category: 'Algoritma' },
    { id: 28, question: 'Saat membuat game sederhana, seorang siswa memutuskan untuk fokus pada logika permainan terlebih dahulu, dan menunda pekerjaan membuat grafik dan suara. Pendekatan ini mencerminkan pilar...', options: ['Abstraksi (fokus pada hal penting lebih dulu)', 'Dekomposisi (membagi tugas)', 'Pengenalan pola', 'Algoritma rendering'], correctAnswer: 0, explanation: 'Memilih fokus pada logika inti lebih dulu dan mengabaikan detail visual untuk sementara adalah abstraksi.', category: 'Abstraksi' },
    { id: 29, question: 'Sebuah smartwatch dapat memantau detak jantung pengguna dan memperingatkan jika detak jantung terlalu tinggi saat berolahraga. Untuk memberikan peringatan yang akurat, smartwatch menggunakan...', options: ['Algoritma yang membandingkan data detak jantung dengan ambang batas tertentu', 'Dekomposisi jantung', 'Abstraksi warna jam', 'Pengenalan pola warna tali jam'], correctAnswer: 0, explanation: 'Smartwatch menggunakan algoritma: jika detak jantung > ambang batas, kirim peringatan.', category: 'Algoritma' },
    { id: 30, question: 'Mengapa berpikir komputasional dianggap sebagai keterampilan penting bagi siswa di abad ke-21, meskipun mereka tidak semua akan menjadi programmer?', options: ['Karena berpikir komputasional hanya berguna untuk membuat aplikasi', 'Karena berpikir komputasional membekali kita dengan kemampuan memecahkan masalah secara sistematis, logis, dan efisien di berbagai bidang kehidupan', 'Karena semua pekerjaan di masa depan akan menggunakan komputer', 'Karena berpikir komputasional wajib untuk lulus sekolah'], correctAnswer: 1, explanation: 'Berpikir komputasional bukan hanya tentang coding, melainkan tentang cara berpikir sistematis untuk memecahkan masalah.', category: 'Konsep Dasar' },
  ],
}

// Helper functions
export function getTypingText(gradeLevel: GradeLevel): string {
  return TYPING_TEXTS[gradeLevel] ?? TYPING_TEXTS['7A']
}

export function getQuestions(gradeLevel: GradeLevel | string): Question[] {
  // ── FIX Bug A: Jangan fallback ke soal SMP untuk siswa SMK ──
  // Sebelumnya: "11DKV".charAt(0) = '1' → QUESTIONS_BY_GRADE['1'] undefined
  // → fallback ke QUESTIONS_BY_GRADE['7'] (soal SMP kelas 7 — SALAH subjek).
  //
  // Sekarang: Untuk SMK (kelas 11DKV / 12DKV / atau string yang dimulai
  // dengan "11"/"12"), return [] langsung. Soal SMK HARUS datang dari
  // database via /api/content/questions, bukan dari fallback statis SMP.
  // Fallback [] akan menampilkan pesan "soal tidak tersedia" di UI,
  // bukan menampilkan soal SMP yang salah.
  const kelas = String(gradeLevel || '')
  if (kelas.startsWith('11') || kelas.startsWith('12')) {
    return []
  }
  const tier = kelas.charAt(0) as '7' | '8' | '9'
  return QUESTIONS_BY_GRADE[tier] ?? []
}

// Cek apakah teks menggunakan format markdown (kelas 9)
export function isStructuredText(gradeLevel: GradeLevel): boolean {
  return gradeLevel.startsWith('9')
}

// Hitung jumlah heading (#, ##, ###) di teks markdown
export function countHeadings(text: string): { h1: number; h2: number; h3: number } {
  const lines = text.split('\n')
  let h1 = 0, h2 = 0, h3 = 0
  for (const line of lines) {
    if (line.startsWith('### ')) h3++
    else if (line.startsWith('## ')) h2++
    else if (line.startsWith('# ')) h1++
  }
  return { h1, h2, h3 }
}

// Hitung jumlah heading di teks sumber
export function getSourceHeadings(gradeLevel: GradeLevel): { h1: number; h2: number; h3: number } {
  return countHeadings(getTypingText(gradeLevel))
}

// Backward compatibility exports
export const TYPING_TEXT = TYPING_TEXTS['9A']
export const QUESTIONS = QUESTIONS_BY_GRADE['9']

export const GRADE_OPTIONS: GradeLevel[] = ['7A', '7B', '7C', '8A', '8B', '8C', '9A', '9B']
